### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by tokidi** [iLLeniumStudios/fivem-appearance#1]
Ped models set for player license, so only with that license can take ped and others cant

**Comment by waseem-h** [comment]
@tokidi there's already ped menu support. You can create a new group and then assign that group to the ped menu users using ACL commands. I will add a guide on how to do this later

**Comment by TheiLLeniumStudios** [comment]
@tokidi There's already support for that using ped menu. All you need to do is create a new group, assign your players license to that group using ACL's and then change the config option Config.UsePedMenu to `true` and Config.PedMenuGroup to `ped` and then only players who are added to the `ped` group using ACL will be able to use custom peds
