### ISSUE TITLE
Players loading in as Base Peds

### ISSUE THREAD

**Issue by DarrianJCairns** [iLLeniumStudios/fivem-appearance#10]
Had a lot of reports now for this sadly. Seems to happen when a server restart occurs.

I have migrated the skins twice (second time skipped them).

Anyone else got this?

**Comment by TheiLLeniumStudios** [comment]
@DarrianJCairns feel free to join my discord and I can help debug the issue with you to push a fix

**Comment by TheiLLeniumStudios** [comment]
@DarrianJCairns I have just tested it on a new server and have not been able to reproduce your issue. If you still see the issue with the latest version, seek out for support in the Discord. Closing it for now
