### ISSUE TITLE
frozen in place after character creation?

### ISSUE THREAD

**Issue by Monkerai** [iLLeniumStudios/fivem-appearance#101]
[https://streamable.com/3zb2lj](url) i am having an issue with my server where my character is frozen in place after creation however after a relog or /logout the character works 100%. I'm not sure if it has anything to do with my multicharacter script or whether someone here is the issue. Would anyone by chance know a possible fix to this. I have proceeded to contact the developer of the multicharacter script to ask the same questions but haven't received a response.

**Comment by TheiLLeniumStudios** [comment]
@Monkerai what multicharacter are you using?

**Comment by Monkerai** [comment]
im using staxzs-multicharacter.

**Comment by TheiLLeniumStudios** [comment]
@Monkerai I don't own that multicharacter so can't say what's causing the issue. If you could contact me on Discord and show me how it works and what's the code, I'll be able to help you out

**Comment by TheiLLeniumStudios** [comment]
Solved
