### ISSUE TITLE
Tattooproblem

### ISSUE THREAD

**Issue by GhostLegionRP** [iLLeniumStudios/fivem-appearance#102]
If you have tattoos they are not saved across outfits

**Comment by TheiLLeniumStudios** [comment]
@GhostLegionRP I'm not able to reproduce your issue. Just tried it with a new character, added tattoos, saved default outfit, changes clothes, saved it as outfit, switched between 2 outfits and the tattoos were there on both of them

**Comment by GhostLegionRP** [comment]
if you have a saved outfit without tattoos an one with, then you switch the outfits the tattoos switches too

**Comment by TheiLLeniumStudios** [comment]
@GhostLegionRP Tattoos are part of your skin, not outfits, so that is intended behavior. The only parts that are considered an outfit type are components and props. Everything else will stay be the same between different outfits
