### ISSUE TITLE
ped starting at 50% health

### ISSUE THREAD

**Issue by SonofGlensow** [iLLeniumStudios/fivem-appearance#103]
Hi, i'm using last version of fivem-appearance. When the player starts the game, he stays with 50% health and does not increase health when using the bandage. Same problem with /refreshskin command

**Comment by peppinoita** [comment]
Use the release and not the main development branch

**Comment by RenggoStarz** [comment]
i same problem ..

**Comment by TheiLLeniumStudios** [comment]
Use the latest release v3.8.0 and not main. You're supposed to use releases. Main branch can be unstable and is not recommended to use @SonofGlensow @RenggoStarz

**Comment by RenggoStarz** [comment]
> Use the latest release v3.8.0 and not main. You're supposed to use releases. Main branch can be unstable and is not recommended to use @SonofGlensow @RenggoStarz

already work @TheiLLeniumStudios  yesterday i try download in main version is fix
