### ISSUE TITLE
Qb-multicharacter ped spawn

### ISSUE THREAD

**Issue by IllInuz** [iLLeniumStudios/fivem-appearance#107]
not sure if its me.

But it seems like clientside of the qb-multichar is not allowing the ped to be spawned with the selected clothing on.

`                    data = json.decode(data)
                    TriggerEvent('qb-clothing:client:loadPlayerClothing', data, charPed)`

Doesn't seem like the event is declared anywhere.

**Comment by IllInuz** [comment]
```
                    data = json.decode(data)
                    exports['fivem-appearance']:setPedAppearance(charPed, data, true)
                    
```

Should be the fix for it ^

**Comment by TheiLLeniumStudios** [comment]
@IllInuz The instructions on fixing qb-multicharacter are already in the docs. Please follow the docs properly
