### ISSUE TITLE
QB core Migration error

### ISSUE THREAD

**Issue by skrubzilla** [iLLeniumStudios/fivem-appearance#108]
![image](https://user-images.githubusercontent.com/5249209/174961097-1df5e852-2929-40b7-9aa5-0fbdb0a7a3dd.png)
Followed the instructions in the guide.. replaced my sql moved over the 2 blocks of code needed for QB-multicharacter and loaded into the server to start the migration. got this error...

**Comment by TheiLLeniumStudios** [comment]
@skrubzilla Download it from the latest release. You are using main and you haven't even removed `-main` from the folder so this will never work

**Comment by skrubzilla** [comment]
Sorry im kind of a noob @TheiLLeniumStudios  Ill do that now and let you know :) thanks for the quick response though.
