### ISSUE TITLE
im getting an error. everything installed correctly

### ISSUE THREAD

**Issue by jaylac2000** [iLLeniumStudios/fivem-appearance#109]
i just installed, latest version. none of my clothing stores. public, gang or job 

![image](https://user-images.githubusercontent.com/53111006/175470911-e6843759-346c-4bc7-b5ed-c3004ed80b59.png)

**Comment by jaylac2000** [comment]
ive restarted my server and everything worked. but after i tried to use my gang one it comes with same error than nothing works. so something to do with this..
![image](https://user-images.githubusercontent.com/53111006/175491957-01d19bf6-cd01-4d0d-ad99-b1bd237046a2.png)
im assuming maybe no preset?

**Comment by TheiLLeniumStudios** [comment]
@jaylac2000 you should be using the latest release 3.8.3, and not main

**Comment by jaylac2000** [comment]
it is from releases...

**Comment by TheiLLeniumStudios** [comment]
Okay so I just checked and it's because you have to define outfits for that gang as well. If you just add a clothing room without telling what clothes should be there, then it will throw this error. See an example of police at the end of the config and make an outfit for the lostmc gang @jaylac2000

**Comment by jaylac2000** [comment]
Aha, ok. Ty
