### ISSUE TITLE
Male and Female Exclusive Tattoos Show For the Other Sex

### ISSUE THREAD

**Issue by dennrick** [iLLeniumStudios/fivem-appearance#11]
Issue:  Male exclusive and female exclusive tattoos are still in the tattoo shop list for the other sex.  This causes players to think that a tattoo isn't working.  

Is it possible to exclude these from a male/female character as the hash for them in the json file is blank like other tattoo scripts.

**Comment by TheiLLeniumStudios** [comment]
@dennrick I'll see what I can do about that. Thanks for bringing it up

**Comment by TheiLLeniumStudios** [comment]
Now supported in [v3.2.1](https://github.com/iLLeniumStudios/fivem-appearance/releases/v3.2.1)
