### ISSUE TITLE
Character creation not saving ped

### ISSUE THREAD

**Issue by WhoopsIJust** [iLLeniumStudios/fivem-appearance#113]
Currently when you create a character, you can still select do not save for the first time, which will bug the character as nothing will save. I have saved a default version as a fail safe to ensure people can access their ped. however on first creation can we remove the cancel option as a player needs to save their customisation.

**Comment by TheiLLeniumStudios** [comment]
Feature released in https://github.com/iLLeniumStudios/fivem-appearance/releases/tag/v3.9.0
