### ISSUE TITLE
Does showblip still function?

### ISSUE THREAD

**Issue by skrubzilla** [iLLeniumStudios/fivem-appearance#117]
![image](https://user-images.githubusercontent.com/5249209/176975088-820d3706-e7c5-47f7-8797-d51f81b662e0.png)
I have some stores set show blip to false which was working to hide the blip before I updated. Was that changed or stopped working?

**Comment by TheiLLeniumStudios** [comment]
@skrubzilla What exactly is your configuration? Have you used showBlip = false to hide specific blips or hidden all using global show = false and showBlip = true for specific ones?

**Comment by skrubzilla** [comment]
So I can't find anything in the config for global show = false for blips.. i have 4 at the bottom of stores set to false and its still showing them on the map
