### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by MLECZKOO** [iLLeniumStudios/fivem-appearance#124]
can u provide source code instead of compiled js?
Like this [https://github.com/franfdezmorales/fivem-appearance/tree/main/web](https://github.com/franfdezmorales/fivem-appearance/tree/main/web)

![image](https://user-images.githubusercontent.com/108586447/177017313-2ecf9a44-f695-475c-bb73-ba8bfc673974.png)
![image](https://user-images.githubusercontent.com/108586447/177017329-54d2ed51-09f1-4685-880a-0f0b119e9bc2.png)

**Comment by TheiLLeniumStudios** [comment]
I will release it at some point. But not at the moment @MLECZKOO

**Comment by MLECZKOO** [comment]
> I will release it at some point. But not at the moment @MLECZKOO

Any reason that u keep this closed source?
I Can't even translate this.
