### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by GetBackJames** [iLLeniumStudios/fivem-appearance#130]
I have been getting this error in are consol but nothing in game would you know why?

https://cdn.discordapp.com/attachments/948147398323085342/994906294366519406/unknown.png

**Comment by ag-izzy** [comment]
Delete player_outfits table from the database
Create the player_outfits table using the  [SQL ](https://github.com/qbcore-framework/qb-clothing/blob/main/qb-clothing.sql)

**Comment by GetBackJames** [comment]
Alright i will give this a try

**Comment by TheiLLeniumStudios** [comment]
@GetBackJames is the issue resolved now?

**Comment by TheiLLeniumStudios** [comment]
Closing this as a non-issue
