### ISSUE TITLE
Streamed clothing

### ISSUE THREAD

**Issue by Worleybird541** [iLLeniumStudios/fivem-appearance#138]
At certain times of the day, there becomes a point where players that connect in to the server no longer have any clothes available to them from the streamed clothing file, and the players that were in server when going to clothing store can no longer see any of the add on clothing. any possible solutions to this? is this a fivem-appearance issue?

**Comment by TheiLLeniumStudios** [comment]
Interesting. I haven't seen this issue before but I'm pretty sure fivem-appearance has nothing to do with it. May I ask what FiveM build are you running? 2545 or 2612?

**Comment by Worleybird541** [comment]
2372

**Comment by TheiLLeniumStudios** [comment]
@Worleybird541 try going to 2612 or 2545 and see if its the same issue

**Comment by TheiLLeniumStudios** [comment]
Closing as not reproduceable
