### ISSUE TITLE
Clothing issue

### ISSUE THREAD

**Issue by bcrossen95** [iLLeniumStudios/fivem-appearance#141]
When i try to add tattoos and want to see the skin, i go to the icon under the camera in the menu. when i toggle the shirt, it goes to another shirt. How do i fix that to make it where he is shirtless?

**Comment by TheiLLeniumStudios** [comment]
@bcrossen95 you have custom clothing that's why. Read the instructions in the #faq channel of my discord at: https://discord.illenium.dev
