### ISSUE TITLE
Character skin is not loading

### ISSUE THREAD

**Issue by Dk1122** [iLLeniumStudios/fivem-appearance#152]
character skin is not loading
![Screenshot 2022-08-22 215239](https://user-images.githubusercontent.com/97806363/185972009-fd0fa827-aba4-4a43-b251-94d28ea1b429.jpg)

**Comment by TheiLLeniumStudios** [comment]
@Dk1122 you haven’t followed the docs to setup multi character. It’s not an issue, rather something that you haven’t done as per the docs

**Comment by istoking** [comment]
I had the same issue, but did follow the docs. The qb-multicharacter document says to add `local model = joaat(skinData.model)` which throws an error for me.

**Comment by TheiLLeniumStudios** [comment]
@istoking update qb-multicharacter. It needs to have lua54

**Comment by istoking** [comment]
> @istoking update qb-multicharacter. It needs to have lua54

Got it working now, thanks
