### ISSUE TITLE
Unable to cancel when creating your character

### ISSUE THREAD

**Issue by xchopin** [iLLeniumStudios/fivem-appearance#153]
Version used: latest QBCore with latest fivem-appareance

When you create your character and you click on save you can only confirm, it's missing the cancel button. I have checked in the other shops I don't have this issue

**Comment by TheiLLeniumStudios** [comment]
Hi @xchopin This is intended behaviour. It was done to prevent players cancelling during initial character creation

**Comment by xchopin** [comment]
Just to make sure we are talking about the same thing :  I was meaning the cancellation button in the **confirmation modal** (to go back to edition of your character), not the exit button.

**Comment by TheiLLeniumStudios** [comment]
@xchopin yeah it kind of prevents the user to go back and edit the 1st time but it should be okay for the most part. I'll see if I can revert it so that players can go back to continue editing while not being able to exit out without saving at the same time
