### ISSUE TITLE
Only working with default qb-multicharacter

### ISSUE THREAD

**Issue by ChickenDipper1** [iLLeniumStudios/fivem-appearance#154]
I have installed this and it works fine after making require changes to qb-multicharacter, but I cannot get it to work with either marcostom32/qb-multicharacter or OwenT1/qb-multicharacter. 
No matter what I do with these scripts, the character creator never loads on spawn you just get the spawn menu and are a default ped.

**Comment by TheiLLeniumStudios** [comment]
@ChickenDipper1 its not an issue with fivem-appearance. You didn't configure it correctly or they're too old and need to be updated in order to work with fivem-appearance
