### ISSUE TITLE
bad arguement 

### ISSUE THREAD

**Issue by bamablood94** [iLLeniumStudios/fivem-appearance#158]
Sorry If I missed something or whatever, but I followed the installation and ended up getting an error with default qb-multicharacter.

"@qb-multicharacter/client/main.lua:321: bad argument #1 to 'joaat' (string expected, got nil)"

then get a qb-core error right under it that says "SCRIPT ERROR: error object is not a string"

**Comment by TheiLLeniumStudios** [comment]
Not an issue with fivem-appearance. Update your multicharacter

**Comment by bamablood94** [comment]
Got it working thanks. It was an issue with the database. when looking for the model to load for some reason there was a random number in the model column. I changed it mp_m_freemode_01 and it worked
