### ISSUE TITLE
How to properly blacklist peds?

### ISSUE THREAD

**Issue by TankinTom** [iLLeniumStudios/fivem-appearance#161]
I tried to find a way to dis-allow players to change their ped model to something other than:
        "mp_m_freemode_01"
        "mp_f_freemode_01"
However, when I commented out the rest, everyone was just a template, uncommenting them brought everything back. So how do I prohibit players from changing to a model other than those two?

**Comment by TheiLLeniumStudios** [comment]
@TankinTom you have to remove the others from peds.json while keeping the JSON syntax correct

**Comment by TankinTom** [comment]
Gotcha, I tried to comment them out, and it failed. I'll give that a try and report back!

**Comment by TankinTom** [comment]
Okay, that worked, thanks for the input!

**Comment by TankinTom** [comment]
Adding to this, is there a way to make it so only admins are able to change their ped model?

**Comment by TheiLLeniumStudios** [comment]
@TankinTom see the docs. It has an example for whitelisting peds for certain jobs / gangs / ACEs. In your case if you use ACE permissions and have the admins added to the admin ACE, you can just create a new object and specify the admin ACE and then admins will be able to change to those peds too

**Comment by TheiLLeniumStudios** [comment]
https://docs.illenium.dev/free-resources/fivem-appearance/blacklisting/peds/
