### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Staticdevvv** [iLLeniumStudios/fivem-appearance#162]
How do i set this up doi just piy in in [qb] and start it any thats it or

**Comment by TheiLLeniumStudios** [comment]
You set it up by reading the docs @Staticdevvv

**Comment by Staticdevvv** [comment]
It says press [E] clothing store howdo i remove that
i have it as radical meni

**Comment by TheiLLeniumStudios** [comment]
Read the docs. It explains how to configure radialmenu…
