### ISSUE TITLE
Saving Outfits

### ISSUE THREAD

**Issue by RighteousRP** [iLLeniumStudios/fivem-appearance#177]
We've only run into one issue with this script, every time someone tries to save an outfit it gives us this error, the rest of the script works perfectly fine. We followed the instructions to install, deleted the original "player_outfits" from the SQL and ran the one included with the script. Did a fresh install after, still posing the same issue. 
<img width="552" alt="outfits" src="https://user-images.githubusercontent.com/121272547/209261593-afaefe03-9c0b-4e24-a052-bf51e5346ed7.PNG">

**Comment by TheiLLeniumStudios** [comment]
@RighteousRP not a fivem-appearance issue. You haven't followed the instructions correctly as mentioned in the readme. You need to delete the old table `player_outfits` and then recreate it using the new SQL provided (This is what you have missed / haven't done correctly)

**Comment by STCMFILMZ** [comment]
hello, i dont understand what you mean by recreate it?

**Comment by STCMFILMZ** [comment]
i did everything like the guy did above and still get that same error.
