### ISSUE TITLE
Issue with making other clothing rooms

### ISSUE THREAD

**Issue by holden260** [iLLeniumStudios/fivem-appearance#178]
so im trying to make another clothing room for a firefighter job, but everytime i do, it makes my police one stop working. i get rid of the fire one and the police starts working again. what am i doing wrong?
![Capture](https://user-images.githubusercontent.com/121573451/209852389-82a0676b-0ccc-4c7d-b539-5d8667c09c0a.PNG)

**Comment by TheiLLeniumStudios** [comment]
I'm unable to reproduce with the following config:
```lua
Config.ClothingRooms = {
    {
        job = "police",
        coords = vector4(454.91, -990.89, 30.69, 193.4),
        width = 3,
        length = 3,
        zone = {
            shape = {
                vector2(460.41918945312, -993.11444091797),
                vector2(449.39508056641, -993.60614013672),
                vector2(449.88696289062, -990.23779296875),
                vector2(450.97882080078, -989.71411132812),
                vector2(451.0325012207, -987.89904785156),
                vector2(453.47863769531, -987.76928710938),
                vector2(454.35513305664, -988.46459960938),
                vector2(460.4231262207, -987.94573974609)
            },
            minZ = 30.69 - 1.5,
            maxZ = 30.69 + 1.5,
        }
    },
    {
        job = "ambulance",
        coords = vector4(300.43, -1091.71, 29.34, 166.1),
        width = 3,
        length = 3,
        zone = {
            shape = {
                vector2(306.23294067382, -1098.4616699218),
                vector2(306.1235961914, -1092.9763183594),
                vector2(301.40762329102, -1092.8665771484),
                vector2(301.72256469726, -1098.6369628906)
            },
            minZ = 30 - 1.5,
            maxZ = 30 + 1.5,
        }
    }
}
```

Try enabling debug and see where your zone actually is.

**Comment by holden260** [comment]
i made my zone so it should be correct

**Comment by holden260** [comment]
i fixed it!! thanks man!!

**Comment by holden260** [comment]
but what i cant get working is the work outfits. and i havent even messed with that at all. not even the police ones have worked since i installed the script

**Comment by TheiLLeniumStudios** [comment]
What do you mean you can't get it working? Explain the issue please

**Comment by holden260** [comment]
so when i walk up to the guy in police station and click on work outfits, theirs nothing in their. and i followed the installation word for word. their is also no errors or anything. everything else works fine.

**Comment by TheiLLeniumStudios** [comment]
@holden260 thats not an issue if you’ve enabled player managed outfits because then the owner of the business needs to create work outfits in the boss menu. Disable that if you want config based work outfits

**Comment by holden260** [comment]
oh okay i didnt know i had to do it that way. i got it now. thank you so much for your help sir. i really appreciate it

**Comment by TheiLLeniumStudios** [comment]
No problem. I will close the ticket now
