### ISSUE TITLE
Invisible character at spawn

### ISSUE THREAD

**Issue by zf-development** [iLLeniumStudios/fivem-appearance#29]
So I installed it and followed all the instructions but unfortunatly, the peds are not shown when selecting them in the menu (at first spawn).

Is it possible to get help please?

![image](https://user-images.githubusercontent.com/48424078/167718452-f9a7fd20-ed83-4f77-9146-39b1168efa15.png)

**Comment by TheiLLeniumStudios** [comment]
@zf-development what multicharacter are you using?

**Comment by zf-development** [comment]
qb-multicharacter

**Comment by TheiLLeniumStudios** [comment]
@zf-development I offer support at my discord, feel free to join and I'd be happy to assist you: https://discord.gg/ZVJEkjUTkx

**Comment by TheiLLeniumStudios** [comment]
Closing as its resolved now

**Comment by Dkngrha** [comment]
how to fix?

**Comment by Dkngrha** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/ab0191f5-5376-49ee-afc3-ce9602a29c85" />
