### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ItsAegeus** [iLLeniumStudios/fivem-appearance#3]
Hair grade only seen it done once. It was part of a tattoo shop script for ESX. Just don’t feel like paying the dude $50 again for it on QBCore. If done I’ll give ya something as a show of appreciation.

**Comment by waseem-h** [comment]
@ItsAegeus what do you mean hair grade? Can you please elaborate?

**Comment by ItsAegeus** [comment]
@TheiLLeniumStudios Yeah, so hair grade is basically a fade. GTA online does it for specific hairs so you are not bald. Ill post some photos of it from the old script I used.

Before:
![image](https://user-images.githubusercontent.com/42155010/166121049-6c36f23d-1fe8-42d5-b519-1b043963a18c.png)


After:
![image](https://user-images.githubusercontent.com/42155010/166121040-01da4703-fe0d-433f-a375-b57ca5fc2349.png)

**Comment by TheiLLeniumStudios** [comment]
@ItsAegeus Thanks for the reference. I did notice that problem. I'm not an expert of setting player appearances but it seems like its related to hair decorations. I will see what I can do to fix the issue

**Comment by ItsAegeus** [comment]
> @ItsAegeus Thanks for the reference. I did notice that problem. I'm not an expert of setting player appearances but it seems like its related to hair decorations. I will see what I can do to fix the issue

Alright! The way he did it was just added a slider with the options to the tattoo shop but I'm sure you could think of a better place to put it lol.

**Comment by TheiLLeniumStudios** [comment]
@ItsAegeus Fixed by https://github.com/iLLeniumStudios/fivem-appearance/commit/b69b413312adc7888f1d2cc66782bf32ba56058e

Please get the latest version and let me know if it works for you. Feel free to re-open if there are still issues
