### ISSUE TITLE
blacklist problem

### ISSUE THREAD

**Issue by Filipe0071** [iLLeniumStudios/fivem-appearance#31]
he is not blocking the drawable only the textures

https://streamable.com/z2migp

![image](https://user-images.githubusercontent.com/75763087/167749454-18e1c912-6a1c-4457-8b39-703b5dabd166.png)

**Comment by TheiLLeniumStudios** [comment]
@Filipe0071 If you want to block the whole drawable, you don't need the `textures` section for that drawable. 

```json
masks: [
  {
    "drawable": 14
  }
]
```

This blacklists the whole drawable 14.
