### ISSUE TITLE
Toggle clothing

### ISSUE THREAD

**Issue by ducksdev** [iLLeniumStudios/fivem-appearance#62]
We use addon clothing on our server, so all the default numbers bump up in value. When you toggle shirt in a tattoo shop it throws on some random top. Is it possible to edit the component so we can set it to what we please?

Thanks

**Comment by ShomyTKD** [comment]
Trying to change this as well without any luck.. I changed it for toggling in qb-radialmenu, but can't find where to change default values for taking off clothes in the Appearance script. Thanks in advance!

**Comment by waseem-h** [comment]
@ShomyTKD @ducksdev You have custom clothes added. This is not an issue with fivem-appearance but rather a configuration issue. Join my discord for support https://discord.gg/ZVJEkjUTkx

Check out the #faq channel for explanation on how to fix this

**Comment by TheiLLeniumStudios** [comment]
@ducksdev @ShomyTKD Please join the discord https://discord.gg/ZVJEkjUTkx
And check the #faq channel
