### ISSUE TITLE
[Enhancement] Blacklist certain ped models to certain ranks

### ISSUE THREAD

**Issue by SirOMGitsYOU** [iLLeniumStudios/fivem-appearance#68]
Being able to make certain custom ped models (i.e everything but the default mp m & f models) as we use custom models but as the first menu allows you to set a custom ped model this would allow people to select them

**Comment by TheiLLeniumStudios** [comment]
@SirOMGitsYOU you could essentially just set Config.EnablePedMenu to true and set Config.PedMenuGroup to the lowest group who should have access to all custom peds. If you set it to admin, then it only admins will be able to choose the custom peds. Others will get the default ped based on their gender. You should create a new ACL group called ped, set Config.PedMenuGroup to ped, and then add only the players you want to give the custom peds option

**Comment by SirOMGitsYOU** [comment]
> group called ped, set Config.PedMenuGroup to ped, and then add only the players

Oh perfect, so along pedmenu is set to group admin say, then only admins will see the ped menu on startup character creation? if that's the case then disregard my message :)

**Comment by TheiLLeniumStudios** [comment]
@SirOMGitsYOU correct. Closing this then. Feel free to re-open if it's still relevant
