### ISSUE TITLE
Enhancement: Auto select MP ped based on data provided from QB

### ISSUE THREAD

**Issue by jnccloud** [iLLeniumStudios/fivem-appearance#76]
Currently, players are struggling at first to understand how to customize characters.  A deeper dive identified determine there was no issue, only user error. To help combat this user error, it would be appreciated if the character creation selected the gender from PlayerData and selected that option first in the first time character creation menu.

Resolution: Display MP freemode ped first based on character's gender  from PlayerData to decrease confusion among both newer and seasoned veterans.

A screenshot is attached to give an idea of the struggle:  

![image](https://user-images.githubusercontent.com/58707473/169782127-9b9d22d5-0d54-4439-bc0f-9ae2abe14a25.png)

**Comment by TheiLLeniumStudios** [comment]
This is already the case from what I can see. Can you please confirm @jnccloud ?

**Comment by TheiLLeniumStudios** [comment]
I will close this since this is a non issue now

**Comment by jnccloud** [comment]
Sorry, I just noticed the notification. I will confirm this weekend, as I haven't created a character in a while.
