### ISSUE TITLE
(minor enhancement) Utilize native or lua math to deduct one on the Z axis of a coordinate

### ISSUE THREAD

**Issue by jnccloud** [iLLeniumStudios/fivem-appearance#77]
If you use the built in tools to copy a vector4, it will leave the ped floating in the hair. This would at least avoid that mishap by the less experienced. It could be as simple as `Z - 1` or using the native PlaceObjectOnGroundProperly(ped) which essentially does the same thing.

https://docs.fivem.net/natives/?_0x58A850EAEE20FAA3

**Comment by waseem-h** [comment]
@jnccloud Thank you for letting me know about the native. I wasn't aware of that. Will fix that right away. I'm still learning the natives
