### ISSUE TITLE
2 different menus

### ISSUE THREAD

**Issue by jokernights** [iLLeniumStudios/fivem-appearance#8]
![image](https://user-images.githubusercontent.com/77025615/166403749-ee715ff5-ca0d-4ab0-bd32-2f8212f40194.png)

I have both menus ? I did delete tattoo shops and qb-clothing and followed the instructions.. this paticular one is in the barber shop.. the police station only shows the old options . is there something i missed?

**Comment by TheiLLeniumStudios** [comment]
@jokernights you haven't removed qb-clothing properly. Please follow the instructions carefully as described in the readme

**Comment by jokernights** [comment]
> @jokernights you haven't removed qb-clothing properly. Please follow the instructions carefully as described in the readme

I followed it to a tee and I no longer have qb clothing in my server files it’s deleted completely?
