### ISSUE TITLE
 take off the clothes.

### ISSUE THREAD

**Issue by SeriumTW** [iLLeniumStudios/fivem-appearance#87]
I don't know how to replace the customization clothes to take off the clothes. HELP

**Comment by SeriumTW** [comment]
![image](https://user-images.githubusercontent.com/79084923/170367960-e6362c2a-806a-47b4-bae3-57e695de4c02.png)

**Comment by SeriumTW** [comment]
![image](https://user-images.githubusercontent.com/79084923/170367998-b3cd97bc-08f3-4312-92fe-dd11d641b7e0.png)

**Comment by TheiLLeniumStudios** [comment]
Check #faq in my discord: https://discord.illenium.dev
