### ISSUE TITLE
Search for export

### ISSUE THREAD

**Issue by GhostLegionRP** [iLLeniumStudios/fivem-appearance#88]
Is there any export with i can trigger this change ?

`function ApplyPrisonerSkin()

	local playerPed = PlayerPedId()
	local Player = QBCore.Functions.GetPlayerData()
	if DoesEntityExist(playerPed) then
		local DataMale = { --CHANGE CLOTH HERE
				outfitData = {
			['t-shirt'] = {item = 15,texture = 0},
			['torso2']  ={item = 146,texture = 0},
			['decals'] = {item = 0, texutre = 0},
			['arms']     = {item = 119, texture = 0},
			['pants']  ={item = 3, texture = 7},   
			['shoes']  = {item = 12, texture = 12},
			['vest']  = {item = 0, texture = 0},
			['bag']  = {item = 0, texture = 0},
			['mask']  = {item = 0, texture = 0},
			['hat']  = {item = 0, texture = 0},
				}}
		local DataFemale = {
				outfitData = {
			['t-shirt'] = {item = 3,texture = 0},
			['torso2']  ={item = 38,texture = 3},
			['decals'] = {item = 0, texutre = 0},
			['arms']     = {item = 120, texture = 0},
			['pants']  ={item = 3, texture = 15},   
			['shoes']  = {item = 66, texture = 5},
			['vest']  = {item = 0, texture = 0},
			['bag']  = {item = 0, texture = 0},
			['mask']  = {item = 0, texture = 0},
			['hat']  = {item = 0, texture = 0},
				}}
							
		
				if Player.charinfo.gender == 0 then

					TriggerEvent('qb-clothes:client:loadOutfit', DataMale) --Change Here the Clothing resource
				else
				 	TriggerEvent('qb-clothes:client:loadOutfit', DataFemale) --Change Here the Clothing resource

				end

		SetPedArmour(playerPed, 0)
		ClearPedBloodDamage(playerPed)
		ResetPedVisibleDamage(playerPed)
		ClearPedLastWeaponDamage(playerPed)
		ResetPedMovementClipset(playerPed, 0)

	end
end`

**Comment by TheiLLeniumStudios** [comment]
```lua
RegisterNetEvent('qb-clothing:client:loadOutfit', DataMale)
```

**Comment by hasidu** [comment]
how we can do it for esx ?
