### ISSUE TITLE
job clothes problems with women clothing

### ISSUE THREAD

**Issue by xiaoff13** [iLLeniumStudios/fivem-appearance#91]
job clothes problems with women's clothing
After changing work clothes when my character is female, the clothes are displayed as men's clothes

**Comment by TheiLLeniumStudios** [comment]
@xiaoff13 You need to choose female when you sign register on the multicharacter screen. It is not based on the ped, so if you've set male, then you will still see male clothes even if you switch to the female ped

**Comment by xiaoff13** [comment]
Owhhhhhhhh i see
That's it! Thank you for helping me solve this problem

**Comment by TheiLLeniumStudios** [comment]
@xiaoff13 no problem. Can we close this issue now?

**Comment by xiaoff13** [comment]
> @xiaoff13 no problem. Can we close this issue now?

yeah sure
