### ISSUE TITLE
[QUESTION] Clothes to -1

### ISSUE THREAD

**Issue by GhostLegionRP** [iLLeniumStudios/fivem-appearance#92]
Hey, is there a possibility to set the clothes like for example shirts to -1

**Comment by TheiLLeniumStudios** [comment]
@GhostLegionRP setting it to -1 has no effect as far as I know. Why would you need to do it?

**Comment by GhostLegionRP** [comment]
i need it to hide clothes completely, i have the problem that i wear jackets partly as shirts and set the shirts themselves to 0 but then the white shirt shows through

**Comment by TheiLLeniumStudios** [comment]
@GhostLegionRP Components have no effect when they are set to -1 so it will not work the way you want it to work

**Comment by GhostLegionRP** [comment]
@TheiLLeniumStudios Could you make this somehow functional ?
Because you look even it they somehow strange

**Comment by Soldat20** [comment]
Just set your shirt to 15 for male and 11 or 14 for female. Its always been a blank spot since FiveM started just for this matter.
