### ISSUE TITLE
[BUG] PEDS not spawning

### ISSUE THREAD

**Issue by GhostLegionRP** [iLLeniumStudios/fivem-appearance#93]
The peds generally do not spawn, an error in F8 or server console does not come up.

**Comment by TheiLLeniumStudios** [comment]
@GhostLegionRP They only spawn if you have Config.UseTarget = true. Check the config please, or provide reproduction steps

**Comment by GhostLegionRP** [comment]
@TheiLLeniumStudios Oh so i thought the peds spawn on without target like normal qb-clothing =)
